config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  get 'welcome/index'

  resources :orders
  resources :menus

  root 'home#index'

end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  # attr_accessible :dish, :price

  def self.search(search)
    if search
      where('dish LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base

  # validates :terms_of_service, acceptance: { accept: 'yes' }
  validates :name, presence: true, :uniqueness => true, length: { maximum: 40 }
  validates :item, presence: true, length: { maximum:30 }
  validates :item, format: { with: /\A[a-z\d\s]*\Z/i, :message => 'ordered must only be one!!' }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  helper_method :sort_column, :sort_direction
  def index
    @menus = Menu.search(params[:search]).order(sort_column + ' ' + sort_direction)
  end


  def show
    @menu = Menu.find(params[:id])
  end

  def new
  end

  def create
    @menu = Menu.new(menu_params)

    @menu.save
    redirect_to @menu
  end

  private
    def menu_params
      params.require(:menu).permit(:dish, :price)
    end
    def sort_column
      Menu.column_names.include?(params[:sort]) ? params[:sort] : "dish"
    end
    def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  # def menu
  #     @order = Order.new
  # end

  def new
    @order = Order.new
  end

  def edit
    @order = Order.find(params[:id])
  end


  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to @order
    else
      render 'new'
    end
  end

  def update
    @order = Order.find(params[:id])

    if @order.update(order_params)
      redirect_to @order
    else
      render 'edit'
    end
  end


  private
    def order_params
      params.require(:order).permit(:name, :item)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction), {:class => css_class}
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<link href='http://fonts.googleapis.com/css?family=Petit+Formal+Script' rel='stylesheet' type='text/css'>

<% if member_signed_in? %>
<!-- <link href='http://fonts.googleapis.com/css?family=Petit+Formal+Script' rel='stylesheet' type='text/css'> -->

</br>
<h3 id="ord">You have succesfully signed in!! :)</h3>
<!-- <h3>Proceed with your order from below</h3> -->
</br></br></br>
<%= link_to 'New Order', new_order_path, class: 'btn btn-primary btn-xs' %> |
<%= link_to 'Menu', menus_path, class: 'btn btn-success btn-xs' %>  |
<%= link_to "Sign Out", destroy_member_session_path, :method => :delete, class: 'btn btn-danger btn-xs' %>


<% else %>
<link href='http://fonts.googleapis.com/css?family=Special+Elite' rel='stylesheet' type='text/css'>
</br>
<h1 id="wel"> Welcome to ZoomCar Special Friday</h1></br></br></br></br>
<h5 id="sig"> Already have an account?
  <%= link_to "Sign In", new_member_session_path, :method => :get, class: 'btn btn-primary btn-xs' %>
</h5>

<h5 id="sig"> Don't have an account?
  <%= link_to "Sign up", new_member_registration_path, :method => :get, class: 'btn btn-success btn-xs' %>
</h5>
<% end %>

app/views/layouts/application.html.erb
<link href='http://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
<!DOCTYPE html>
<html>
<head>
  <!-- <title>Fridaymenu</title> -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://js.stripe.com/v2/' %>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet"></link>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet"></link>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"></link>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="./" class="navbar-brand" id="nav">ZoomCar</a><a href="./" class="navbar-brand" id="self">  : Self-Drive For The Self-Driven </a>

      </p>
    </div>
    <!-- <p class="navbar-text pull-right"> member.username</p> -->
    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <!-- <li>
          <a href="#">Getting started</a>
        </li> -->
				<!-- <li class="dropdown">
	        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
	        <ul class="dropdown-menu">
	          <li><a href="#">Sign Out</a></li> -->
	          <!-- <li><a href="#"></a></li>
	          <li><a href="#">Something else here</a></li>
	          <li><a href="#">Separated link</a></li>
	          <li><a href="#">One more separated link</a></li> -->
	        <!-- </ul>
	      </li> -->
        <!-- <li>
          <a href="#">Components</a>
        </li>
        <li>
          <a href="#">JavaScript</a>
        </li>
        <li class="active">
          <a href="#">Customize</a>
        </li> -->
      </ul>
    </nav>
  </div>
</header>
  <div id="main-container" class="container">
      <div class="row">
        <div class="col-md-offset-3">
          <!-- <h3>Friday menu</h3> -->
        </div>
        <div class="col-md-offset-3">
          <%= yield %>
        </div>
      </div>
  </div>
</body>
</html>

app/views/menus/_menu.html.erb
<link href='http://fonts.googleapis.com/css?family=Dancing+Script' rel='stylesheet' type='text/css'>
<!-- </br> -->
<h4 id="sort"> P.S. : you can sort the menu in alphabetical order or by price </h4>

<table class="tabel table-hover table-bordered table-condensed", cellspacing="20">
    <tr>

      <th><%= sortable "dish" %></th>
      <th><%= sortable "price" %></th>
      <!-- <th><%= link_to "Dish", :sort => "dish" %></th>
      <th><%= link_to "Price", :sort => "price" %></th> -->
      <!-- <th>Dish</th>
      <th>Price</th> -->
    <th colspan="2"></th>
    </tr>
 
   <% @menus.each do |menu| %>
      <tr>

        <td><%= menu.dish %></td>
        <td><%= menu.price %></td>
      </tr>
    <% end %>
</table>

app/views/menus/index.html.erb
<!-- <link href='http://fonts.googleapis.com/css?family=Petit+Formal+Script' rel='stylesheet' type='text/css'> -->

<h3>            </h3>
<h3>            </h3>
<h3 id="lis">Listing Menu</h3>

 
<%= form_tag menus_path, :method => 'get', :id => "dish_search" do %>
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
<!-- <link href='http://fonts.googleapis.com/css?family=Dancing+Script' rel='stylesheet' type='text/css'>
</br>
<h4 id="sort"> P.S. : you can sort the menu in alphabetical order or by price </h4>

<table class="tabel table-hover table-bordered table-condensed", cellspacing="20">
    <tr>

      <th><%= sortable "dish" %></th>
      <th><%= sortable "price" %></th> -->
      <!-- <th><%= link_to "Dish", :sort => "dish" %></th>
      <th><%= link_to "Price", :sort => "price" %></th> -->
      <!-- <th>Dish</th>
      <th>Price</th> -->
    <!-- <th colspan="2"></th>
    </tr>
 
   <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.dish %></td>
        <td><%= menu.price %></td>
      </tr>
    <% end %>
</table> -->
<div id="menu"><%= render 'menu' %></div>
<%= link_to 'Back', new_order_path, class: 'btn btn-primary btn-xs' %>

app/views/menus/index.js.erb
$('#menu').html(<%= escape_javascript(render("menu")) %>);

app/views/menus/new.html.erb
<link href='http://fonts.googleapis.com/css?family=Petit+Formal+Script' rel='stylesheet' type='text/css'>

<h1 id="menu"> Menu for You </h1>
<%= form_for :menu, url: menus_path do |f| %>  <p>
    <%= f.label :dish %><br>
    <%= f.text_field :dish %>
  </p>
 
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/menus/show.html.erb
<p>
  <strong>Dish:</strong>
  <%= @menu.dish %>
</p>
 
<p>
  <strong>Price:</strong>
  <%= @menu.price %>
</p>
<%= link_to 'Back', orders_path %>

app/views/orders/_form.html.erb
<%= form_for @order do |f| %>

  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@order.errors.count, "error") %> prevented you from placing your order:
      </h2>
      <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :item %><br>
    <%= f.text_area :item %>
  </p>

  <p>
    <%= f.submit %>
  </p> -->

  <div class="field form-group">
      <%= f.label :name, class: 'col col-lg-2 control-label' %><br />
      <%= f.text_field :name, class: 'form-control', autofocus: true %>
  </div>

  <div class="field form-group">
      <%= f.label :item, class: 'col col-lg-2 control-label' %><br />
      <%= f.text_area :item, class: 'form-control', autofocus: true %>
  </div>

  <div class="actions form-group">
      <div class="col-lg-offset-0 col-offset-2">
        <%= f.submit class: "btn btn-default"%>
      </div>
  </div>

<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>
<%= render 'form' %> 
<!-- <%= form_for :order, url: order_path(@order), method: :patch do |f| %>
 
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@order.errors.count, "error") %> prohibited you from placing your order:
      </h2>
      <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :item %><br>
    <%= f.text_area :item %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %> -->
<%= link_to 'Menu', orders_path, class: 'btn btn-primary btn-xs' %>  |
<%= link_to 'Back', orders_path, class: 'btn btn-primary btn-xs' %>

app/views/orders/index.html.erb
<link href='http://fonts.googleapis.com/css?family=Petit+Formal+Script' rel='stylesheet' type='text/css'>
<% if member_signed_in? %>
<h3 id="ord">Listing All Orders</h3>


<!-- <td><%= link_to "Sign Out", destroy_member_session_path, :method => :delete %></td> -->
<div class="container">
  <table class="tabel table-hover table-bordered table-condensed", cellspacing="10">  
    <thead>
      <tr>
        <th>Name</th>
        <th>Item</th>
        <th colspan="2"></th>
      </tr>
    </thead>
</div>  
<% @orders.each do |order| %>
    <tr>
      <td><%= order.name %></td>
      <td><%= order.item %></td>
      <!-- <td><%= link_to 'Edit', edit_order_path(order) %></td> -->
    </tr>
  <% end %>
</table>
<%= link_to 'New Order', new_order_path, class: 'btn btn-primary btn-xs' %> |

<td><%= link_to "Sign Out", destroy_member_session_path, :method => :delete, class: 'btn btn-danger btn-xs' %></td> |
<%= link_to 'Print', 'Index', :onclick => 'window.print();return false;', class: 'btn btn-primary btn-xs'%>

<% else %>
<h3 id="ord">Listing All Orders</h3>


<!-- <td><%= link_to "Sign Out", destroy_member_session_path, :method => :delete %></td> -->
<div class="container">
  <table class="tabel table-hover table-bordered table-condensed", cellspacing="10">  
    <thead>
      <tr>
        <th>Name</th>
        <th>Item</th>
        <th colspan="2"></th>
      </tr>
    </thead>
</div>  
<% @orders.each do |order| %>
    <tr>
      <td><%= order.name %></td>
      <td><%= order.item %></td>
      <!-- <td><%= link_to 'Edit', edit_order_path(order) %></td> -->
    </tr>
  <% end %>
</table>
<%= link_to 'New Order', new_order_path, class: 'btn btn-primary btn-xs' %> |

<%= link_to "Sign In", new_member_session_path, :method => :get, class: 'btn btn-info btn-xs' %>|
<%= link_to 'Print', 'Index', :onclick => 'window.print();return false;', class: 'btn btn-primary btn-xs'%>
<% end %>

app/views/orders/new.html.erb
<link href='http://fonts.googleapis.com/css?family=Petit+Formal+Script' rel='stylesheet' type='text/css'>

<% if member_signed_in? %>
<h2 id="new">New Order</h2>
<%= render 'form' %>
<h4 id="search"> Please narrow down your dish from below or visit the Menu section </h4>
<%= form_tag menus_path, :method => 'get', :id => "dishe_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<%= link_to 'Menu', menus_path, class: 'btn btn-success btn-xs' %>  |
<%= link_to 'All orders', orders_path, class: 'btn btn-info btn-xs' %>      |
<%= link_to "Sign Out", destroy_member_session_path, :method => :delete, class: 'btn btn-danger btn-xs' %>

<% else %>
<link href='http://fonts.googleapis.com/css?family=Special+Elite' rel='stylesheet' type='text/css'>
<h3 id="ord">You are not logged in!! :(</h3>
<p></br></br>
<h4 id="goto" >Please goto <a href="http://localhost:3000/members/sign_in"</a>sign in</h4>
</p>
<% end %>

app/views/orders/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Item:</strong>
  <%= @order.item %>
</p>

<%= link_to 'Back', orders_path, class: 'btn btn-primary btn-xs' %> |
<%= link_to 'Edit', edit_order_path, class: 'btn btn-info btn-xs'%>  |
<%= link_to "Sign Out", destroy_member_session_path, :method => :delete, class: 'btn btn-danger btn-xs' %>

app/views/welcome/index.html.erb
<h1>Friday Order Menu!</h1>
<%= link_to 'Menu', controller: 'menus' %>